// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.1-0.20240325090356-a14414f04fdd DO NOT EDIT.
package restapi

// Defines values for AlertType.
const (
	AlertTypeAlert   AlertType = "alert"
	AlertTypeError   AlertType = "error"
	AlertTypeInfo    AlertType = "info"
	AlertTypeSuccess AlertType = "success"
	AlertTypeWarning AlertType = "warning"
)

// Defines values for GetHtmlAlertParamsTyp.
const (
	GetHtmlAlertParamsTypAlert   GetHtmlAlertParamsTyp = "alert"
	GetHtmlAlertParamsTypError   GetHtmlAlertParamsTyp = "error"
	GetHtmlAlertParamsTypInfo    GetHtmlAlertParamsTyp = "info"
	GetHtmlAlertParamsTypSuccess GetHtmlAlertParamsTyp = "success"
	GetHtmlAlertParamsTypWarning GetHtmlAlertParamsTyp = "warning"
)

// Id Primary key identifier
type Id = int64

// IdObject defines model for IdObject.
type IdObject struct {
	// Id Primary key identifier
	Id *Id `json:"id,omitempty"`
}

// IdObjects defines model for IdObjects.
type IdObjects = []IdObject

// IdString String-based Id
type IdString = string

// JSONError defines model for JSONError.
type JSONError struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Link defines model for Link.
type Link struct {
	Html *string `json:"html,omitempty"`

	// Id Primary key identifier
	Id          *Id     `json:"id,omitempty"`
	OriginalUrl *string `json:"originalUrl,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// LinkWithGroup defines model for LinkWithGroup.
type LinkWithGroup struct {
	Group     *string `json:"group,omitempty"`
	GroupId   *int64  `json:"groupId,omitempty"`
	GroupType *string `json:"groupType,omitempty"`
	Html      *string `json:"html,omitempty"`

	// Id Primary key identifier
	Id          *Id     `json:"id,omitempty"`
	OriginalUrl *string `json:"originalUrl,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// LinksWithGroups defines model for LinksWithGroups.
type LinksWithGroups = []LinkWithGroup

// AlertMsg defines model for AlertMsg.
type AlertMsg = string

// AlertType defines model for AlertType.
type AlertType string

// ContextMenuType String-based Id
type ContextMenuType = IdString

// ErrorMsg defines model for ErrorMsg.
type ErrorMsg = string

// GroupFilter defines model for GroupFilter.
type GroupFilter = []string

// GroupTypeFilter defines model for GroupTypeFilter.
type GroupTypeFilter = []string

// IdParameter defines model for IdParameter.
type IdParameter = int64

// LabelId String-based Id
type LabelId = IdString

// LinkId Primary key identifier
type LinkId = Id

// LinkUrl defines model for LinkUrl.
type LinkUrl = string

// MenuItem defines model for MenuItem.
type MenuItem = string

// MetaFilter defines model for MetaFilter.
type MetaFilter map[string]string

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = JSONError

// GetHtmlAlertParams defines parameters for GetHtmlAlert.
type GetHtmlAlertParams struct {
	// Typ Type of alert message to display as HTML
	Typ *GetHtmlAlertParamsTyp `form:"typ,omitempty" json:"typ,omitempty"`

	// Msg Alert message to display as HTML
	Msg *AlertMsg `form:"msg,omitempty" json:"msg,omitempty"`
}

// GetHtmlAlertParamsTyp defines parameters for GetHtmlAlert.
type GetHtmlAlertParamsTyp string

// GetHtmlErrorParams defines parameters for GetHtmlError.
type GetHtmlErrorParams struct {
	// Err Error message to display as HTML
	Err *ErrorMsg `form:"err,omitempty" json:"err,omitempty"`
}

// GetHtmlLinksetParams defines parameters for GetHtmlLinkset.
type GetHtmlLinksetParams struct {
	// Gt Links for a Group Type
	Gt *GroupTypeFilter `form:"gt,omitempty" json:"gt,omitempty"`

	// Grp Links by group of type
	Grp *GroupFilter `form:"grp,omitempty" json:"grp,omitempty"`

	// M Key/Value meta filter for Links
	M *MetaFilter `form:"m,omitempty" json:"m,omitempty"`
}

// PostHtmlLinksetFormdataBody defines parameters for PostHtmlLinkset.
type PostHtmlLinksetFormdataBody struct {
	Action *string `form:"action,omitempty" json:"action,omitempty"`
	LinkId *[]Id   `form:"linkId,omitempty" json:"linkId,omitempty"`
}

// PostHtmlLinksetFormdataRequestBody defines body for PostHtmlLinkset for application/x-www-form-urlencoded ContentType.
type PostHtmlLinksetFormdataRequestBody PostHtmlLinksetFormdataBody

// PostLinksWithGroupsJSONRequestBody defines body for PostLinksWithGroups for application/json ContentType.
type PostLinksWithGroupsJSONRequestBody = LinksWithGroups
