openapi: 3.1.0
info:
  title: SaveTabs Daemon API
  version: 1.0.0
paths:

  /html/context-menu/{contextMenuType}/{id}:
    get:
      summary: Return a context menu for the editable item
      parameters:
      - $ref: '#/components/parameters/ContextMenuType'
      - $ref: '#/components/parameters/IdParameter'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/context-menu/{contextMenuType}/{id}/rename-form:
    get:
      summary: Return a form for renaming an element targeted by a context menu item
      parameters:
      - $ref: '#/components/parameters/ContextMenuType'
      - $ref: '#/components/parameters/IdParameter'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /context-menu/{contextMenuType}/{id}/name:
    put:
      summary: Update name text by context menu type and DB ID
      parameters:
      - $ref: '#/components/parameters/ContextMenuType'
      - $ref: '#/components/parameters/IdParameter'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            $ref: '#/components/schemas/NameToRename'
      responses:
        '200':
          description: The name was updated
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/linkset:
    post:
      summary: Update a set of Links
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                action:
                  type: string
                  nullable: false
                linkId:
                  type: array
                  nullable: false
                  items:
                    $ref: '#/components/schemas/Id'
            encoding:
              action:
                style: form
              linkId:
                style: form
                explode: true
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

    get:
      summary: Return the HTML for a paginated table of links with optional filtering criteria in query parameters
      parameters:
      - $ref: '#/components/parameters/GroupTypeFilter'
      - $ref: '#/components/parameters/GroupFilter'
      - $ref: '#/components/parameters/MetaFilter'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/menu:
    get:
      summary: Return the HTML for the Menu
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/menu/{menuItem}:
    get:
      summary: Return the HTML for the Menu
      parameters:
      - $ref: '#/components/parameters/MenuItem'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/error:
    get:
      summary: HTML-formatted error
      description: Error formatted as Daisy UI alert HTML
      parameters:
      - $ref: '#/components/parameters/ErrorMsg'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /html/alert:
    get:
      summary: HTML-formatted alert
      description: Alert formatted as Daisy UI alert HTML
      parameters:
      - $ref: '#/components/parameters/AlertType'
      - $ref: '#/components/parameters/AlertMsg'
      responses:
        '200':
          $ref: '#/components/responses/HtmlResponse'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /links/with-groups:
    post:
      summary: Adds multiple links, each with group info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinksWithGroups'
      responses:
        '201':
          description: The links were created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdObjects'
        default:
          $ref: '#/components/responses/UnexpectedError'

  /links/by-url/{linkUrl}:
    put:
      summary: Send URL information to be stored
      parameters:
      - $ref: '#/components/parameters/LinkUrl'
      responses:
        '200':
          description: The link was updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdObject'
        '201':
          description: The link were created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdObject'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '409':
          description: Conflict
        '412':
          description: Precondition Failed
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity (WebDAV)
        default:
          $ref: '#/components/responses/UnexpectedError'

  /links/{linkId}:
    get:
      summary: Get information about a Link (URL)
      parameters:
      - $ref: '#/components/parameters/LinkId'
      responses:
        '200':
          description: The link was updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        default:
          $ref: '#/components/responses/UnexpectedError'

  /healthz:
    get:
      summary: Health Check
      description: Check the health status of SaveTabs daemon.
      responses:
        '200':
          description: OK
        '503':
          description: Service Unavailable
        default:
          $ref: '#/components/responses/UnexpectedError'
  /readyz:
    get:
      summary: Readiness Check
      description: Check if SaveTabs daemon is ready to serve.
      responses:
        '200':
          description: OK
        '503':
          description: Service Unavailable
        default:
          $ref: '#/components/responses/UnexpectedError'

components:
  parameters:
    LabelId:
      name: labelId
      in: path
      description: HTML ID attribute for label
      required: true
      schema:
        $ref: '#/components/schemas/IdString'
    ContextMenuType:
      name: contextMenuType
      in: path
      description: Slug for contextMenuType
      required: true
      schema:
        $ref: '#/components/schemas/IdString'
    LinkId:
      name: linkId
      in: path
      description: ID for the link
      required: true
      schema:
        $ref: '#/components/schemas/Id'
    LinkUrl:
      name: linkUrl
      in: path
      description: URL for a link
      required: true
      schema:
        type: string
    GroupTypeFilter:
      description: Links for a Group Type
      in: query
      name: gt
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
    GroupFilter:
      description: Links by group of type
      in: query
      name: grp
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
    MetaFilter:
      description: Key/Value meta filter for Links
      in: query
      name: m
      schema:
        type: object
        additionalProperties:
          type: string
      style: form
      explode: true
    AlertType:
      description: Type of alert message to display as HTML
      in: query
      name: typ
      schema:
        type: string
        enum:
        - alert
        - info
        - success
        - warning
        - error
      style: form
    AlertMsg:
      description: Alert message to display as HTML
      in: query
      name: msg
      schema:
        type: string
      style: form
    ErrorMsg:
      description: Error message to display as HTML
      in: query
      name: err
      schema:
        type: string
      style: form
    MenuItem:
      description: Item label for menu option
      name: menuItem
      in: path
      required: true
      schema:
        type: string

    GroupTypeName:
      name: groupTypeName
      in: path
      description: Name of group type
      required: true
      schema:
        type: string

    GroupType:
      name: groupType
      in: path
      description: One character group type, e.g. 'G', 'C', 'K', 'T', etc.
      required: true
      schema:
        type: string

    GroupSlug:
      name: groupSlug
      in: path
      description: Slug for the group, i.e. lowercased name with only alphanum and dashes
      required: true
      schema:
        type: string

    IdParameter:
      name: id
      in: path
      description: Primary key of database table
      required: true
      schema:
        type: integer
        minimum: 1
        format: int64

  responses:
    NoJSONResponse:
      description: No response to a non-HTML request
      content:
        application/json:
          schema:
            type: string
            example: ""

    HtmlResponse:
      description: HTML or HTML snippet returned successfully
      content:
        text/html:
          schema:
            type: string
            example: "<div>Hello, HTML!</div>"

    IdResponse:
      description: A generic response containing a primary key Id in JSON format
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdObject'
    IdsResponse:
      description: A generic response containing multiple primary key Ids in JSON format
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IdObjects'
    UnexpectedError:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JSONError'
  schemas:
    TypeString:
      type: string
      description: Type of item
      nullable: false
    IdString:
      type: string
      description: String-based Id
      nullable: false
    Id:
      type: integer
      format: int64
      description: Primary key identifier
      nullable: false
    IdObject:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
    IdObjects:
      type: array
      items:
        $ref: '#/components/schemas/IdObject'
    Link:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        originalUrl:
          type: string
          format: uri
          nullable: false
        title:
          type: string
        html:
          type: string
    LinkWithGroup:
      allOf:
        - $ref: '#/components/schemas/Link'
        - type: object
          properties:
            groupId:
              type: integer
              format: int64
              nullable: false
            group:
              type: string
              nullable: false
            groupType:
              type: string
              nullable: false
    NameToRename:
      type: object
      properties:
        name:
          type: string
          description: Name of Item to rename
          nullable: false
      encoding:
        name:
          style: form
    LinkIds:
      type: array
      items:
          type: integer
          format: int64
          description: Primary key identifier
    LinksWithGroups:
      type: array
      items:
        $ref: '#/components/schemas/LinkWithGroup'
    Group:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
        type:
          type: string
          enum: [ category, tag, keyword, tab-group ]
    GroupWithId:
      allOf:
        - $ref: '#/components/schemas/Group'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              description: The unique identifier for the group
    JSONError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    HTMLError:
      type: string

#jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
#security:
#  -
#servers:
#  -
#webhooks:
#externalDocs:
#tags:
#  -

