// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Action struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Content struct {
	ID          int64          `json:"id"`
	LinkID      int64          `json:"link_id"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	Head        string         `json:"head"`
	CreatedTime sql.NullString `json:"created_time"`
	Created     sql.NullInt64  `json:"created"`
}

type Group struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Slug        string         `json:"slug"`
	CreatedTime sql.NullString `json:"created_time"`
	LatestTime  sql.NullString `json:"latest_time"`
	Created     sql.NullInt64  `json:"-"`
	Latest      sql.NullInt64  `json:"latest"`
	Archived    int64          `json:"archived"`
	Deleted     int64          `json:"deleted"`
}

type GroupType struct {
	Type        string         `json:"type"`
	Sort        sql.NullInt64  `json:"sort"`
	Name        sql.NullString `json:"name"`
	Plural      sql.NullString `json:"plural"`
	Description sql.NullString `json:"description"`
}

type History struct {
	ID         int64         `json:"id"`
	ForeignID  sql.NullInt64 `json:"foreign_id"`
	DateTime   sql.NullInt64 `json:"date_time"`
	ActionID   sql.NullInt64 `json:"action_id"`
	ActionData []byte        `json:"action_data"`
}

type Link struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Scheme      string         `json:"scheme"`
	Subdomain   string         `json:"subdomain"`
	Sld         string         `json:"sld"`
	Tld         string         `json:"tld"`
	Port        string         `json:"port"`
	Path        string         `json:"path"`
	Query       string         `json:"query"`
	Fragment    string         `json:"fragment"`
	OriginalUrl string         `json:"original_url"`
	Url         sql.NullString `json:"url"`
	CreatedTime sql.NullString `json:"created_time"`
	VisitedTime sql.NullString `json:"visited_time"`
	Created     sql.NullInt64  `json:"-"`
	Visited     sql.NullInt64  `json:"visited"`
	Archived    int64          `json:"archived"`
	Deleted     int64          `json:"deleted"`
	Parsed      int64          `json:"parsed"`
}

type LinkGroup struct {
	ID          int64          `json:"id"`
	GroupID     int64          `json:"group_id"`
	LinkID      int64          `json:"link_id"`
	CreatedTime sql.NullString `json:"created_time"`
	LatestTime  sql.NullString `json:"latest_time"`
	Created     sql.NullInt64  `json:"created"`
	Latest      sql.NullInt64  `json:"latest"`
}

type Meta struct {
	ID           int64          `json:"id"`
	LinkID       int64          `json:"link_id"`
	Key          string         `json:"key"`
	Value        string         `json:"value"`
	KvPair       string         `json:"kv_pair"`
	CreatedTime  sql.NullString `json:"created_time"`
	ModifiedTime sql.NullString `json:"modified_time"`
	Created      sql.NullInt64  `json:"created"`
	Modified     sql.NullInt64  `json:"modified"`
}

type Var struct {
	ID    int64          `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}
