// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Action struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Content struct {
	ID          int64          `json:"id"`
	LinkID      int64          `json:"link_id"`
	Title       string         `json:"title"`
	Body        string         `json:"body"`
	Head        string         `json:"head"`
	CreatedTime sql.NullString `json:"created_time"`
	Created     sql.NullInt64  `json:"created"`
}

type Group struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	Slug        string         `json:"slug"`
	CreatedTime sql.NullString `json:"created_time"`
	LatestTime  sql.NullString `json:"latest_time"`
	Created     sql.NullInt64  `json:"-"`
	Latest      sql.NullInt64  `json:"latest"`
	Archived    int64          `json:"archived"`
	Deleted     int64          `json:"deleted"`
}

type GroupType struct {
	Type        string         `json:"type"`
	Sort        sql.NullInt64  `json:"sort"`
	Name        sql.NullString `json:"name"`
	Plural      sql.NullString `json:"plural"`
	Description sql.NullString `json:"description"`
}

type GroupsType struct {
	Type           string         `json:"type"`
	Name           sql.NullString `json:"name"`
	Plural         sql.NullString `json:"plural"`
	GroupCount     int64          `json:"group_count"`
	GroupsArchived int64          `json:"groups_archived"`
	GroupsDeleted  int64          `json:"groups_deleted"`
	LinkCount      int64          `json:"link_count"`
	LinksArchived  int64          `json:"links_archived"`
	LinksDeleted   int64          `json:"links_deleted"`
	Sort           sql.NullInt64  `json:"sort"`
}

type History struct {
	ID         int64         `json:"id"`
	ForeignID  sql.NullInt64 `json:"foreign_id"`
	DateTime   sql.NullInt64 `json:"date_time"`
	ActionID   sql.NullInt64 `json:"action_id"`
	ActionData []byte        `json:"action_data"`
}

type Link struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Scheme      string         `json:"scheme"`
	Subdomain   string         `json:"subdomain"`
	Sld         string         `json:"sld"`
	Tld         string         `json:"tld"`
	Port        string         `json:"port"`
	Path        string         `json:"path"`
	Query       string         `json:"query"`
	Fragment    string         `json:"fragment"`
	OriginalUrl string         `json:"original_url"`
	Host        string         `json:"host"`
	Url         string         `json:"url"`
	CreatedTime sql.NullString `json:"created_time"`
	VisitedTime sql.NullString `json:"visited_time"`
	Created     sql.NullInt64  `json:"-"`
	Visited     sql.NullInt64  `json:"visited"`
	Archived    int64          `json:"archived"`
	Deleted     int64          `json:"deleted"`
	Parsed      int64          `json:"parsed"`
}

type LinkGroup struct {
	ID          int64          `json:"id"`
	GroupID     int64          `json:"group_id"`
	LinkID      int64          `json:"link_id"`
	CreatedTime sql.NullString `json:"created_time"`
	LatestTime  sql.NullString `json:"latest_time"`
	Created     sql.NullInt64  `json:"created"`
	Latest      sql.NullInt64  `json:"latest"`
}

type LinkGroupMove struct {
	ID      int64  `json:"id"`
	Role    string `json:"role"`
	GroupID int64  `json:"group_id"`
	LinkID  int64  `json:"link_id"`
}

type LinkGroupMoveException struct {
	Exception     string `json:"exception"`
	FromGroupID   int64  `json:"from_group_id"`
	FromGroupName string `json:"from_group_name"`
	LinkID        int64  `json:"link_id"`
	LinkUrl       string `json:"link_url"`
	ToGroupID     int64  `json:"to_group_id"`
	ToGroupName   string `json:"to_group_name"`
	FromID        int64  `json:"from_id"`
	ToID          int64  `json:"to_id"`
}

type LinkGroupMoveFromTo struct {
	TypeName           string `json:"type_name"`
	FromID             int64  `json:"from_id"`
	ToID               int64  `json:"to_id"`
	FromLinkGroupID    int64  `json:"from_link_group_id"`
	FromLinkGroupFound bool   `json:"from_link_group_found"`
	FromGroupID        int64  `json:"from_group_id"`
	LinkID             int64  `json:"link_id"`
	ToGroupID          int64  `json:"to_group_id"`
	FromGroupName      string `json:"from_group_name"`
	LinkUrl            string `json:"link_url"`
	ToLinkGroupID      int64  `json:"to_link_group_id"`
	ToLinkGroupFound   bool   `json:"to_link_group_found"`
	ToGroupName        string `json:"to_group_name"`
	FromGroupFound     bool   `json:"from_group_found"`
	LinkFound          bool   `json:"link_found"`
	ToGroupFound       bool   `json:"to_group_found"`
}

type LinkGroupMoveHalf struct {
	ID             int64  `json:"id"`
	LinkGroupID    int64  `json:"link_group_id"`
	Role           string `json:"role"`
	GroupName      string `json:"group_name"`
	GroupType      string `json:"group_type"`
	TypeName       string `json:"type_name"`
	LinkID         int64  `json:"link_id"`
	GroupID        int64  `json:"group_id"`
	GroupFound     bool   `json:"group_found"`
	LinkFound      bool   `json:"link_found"`
	LinkGroupFound bool   `json:"link_group_found"`
	LinkUrl        string `json:"link_url"`
}

type Meta struct {
	ID           int64          `json:"id"`
	LinkID       int64          `json:"link_id"`
	Key          string         `json:"key"`
	Value        string         `json:"value"`
	KvPair       string         `json:"kv_pair"`
	CreatedTime  sql.NullString `json:"created_time"`
	ModifiedTime sql.NullString `json:"modified_time"`
	Created      sql.NullInt64  `json:"created"`
	Modified     sql.NullInt64  `json:"modified"`
}

type Var struct {
	ID    int64          `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}
