// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const deleteVar = `-- name: DeleteVar :exec
DELETE FROM var WHERE id = ?
`

func (q *Queries) DeleteVar(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVar, id)
	return err
}

const listFilteredLinks = `-- name: ListFilteredLinks :many
SELECT id, url, created_time, visited_time, created, visited
FROM link
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListFilteredLinks(ctx context.Context, ids []int64) ([]Link, error) {
	query := listFilteredLinks
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.CreatedTime,
			&i.VisitedTime,
			&i.Created,
			&i.Visited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByType = `-- name: ListGroupsByType :many
SELECT id, name, type, slug, created_time, latest_time, created, latest FROM ` + "`" + `group` + "`" + ` WHERE type = ? ORDER BY name
`

func (q *Queries) ListGroupsByType(ctx context.Context, type_ string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Slug,
			&i.CreatedTime,
			&i.LatestTime,
			&i.Created,
			&i.Latest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsType = `-- name: ListGroupsType :many
SELECT DISTINCT
   gt.type,
   gt.name,
   gt.plural,
   COUNT(DISTINCT g.id) AS group_count,
   CAST(CASE WHEN g.ID IS NULL THEN 0
      ELSE COUNT(DISTINCT rg.link_id) END AS INTEGER) AS link_count,
   gt.sort
FROM group_type gt
   LEFT JOIN ` + "`" + `group` + "`" + ` g ON gt.type=g.type
   LEFT JOIN link_group rg ON g.id=rg.group_id
GROUP BY
   gt.sort,
   gt.type,
   gt.name
ORDER BY
   gt.sort
`

type ListGroupsTypeRow struct {
	Type       string         `json:"type"`
	Name       sql.NullString `json:"name"`
	Plural     sql.NullString `json:"plural"`
	GroupCount int64          `json:"group_count"`
	LinkCount  int64          `json:"link_count"`
	Sort       sql.NullInt64  `json:"sort"`
}

func (q *Queries) ListGroupsType(ctx context.Context) ([]ListGroupsTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsTypeRow
	for rows.Next() {
		var i ListGroupsTypeRow
		if err := rows.Scan(
			&i.Type,
			&i.Name,
			&i.Plural,
			&i.GroupCount,
			&i.LinkCount,
			&i.Sort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsWithCounts = `-- name: ListGroupsWithCounts :many
SELECT id, link_count, name, type, slug, type_name, type_plural FROM groups_with_counts_view
`

func (q *Queries) ListGroupsWithCounts(ctx context.Context) ([]GroupsWithCountsView, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupsWithCountsView
	for rows.Next() {
		var i GroupsWithCountsView
		if err := rows.Scan(
			&i.ID,
			&i.LinkCount,
			&i.Name,
			&i.Type,
			&i.Slug,
			&i.TypeName,
			&i.TypePlural,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkIdsByGroupSlugs = `-- name: ListLinkIdsByGroupSlugs :many
SELECT CAST(rg.link_id AS INTEGER) AS link_id
FROM link_group rg
JOIN ` + "`" + `group` + "`" + ` g ON g.id=rg.group_id
WHERE g.slug IN (/*SLICE:slugs*/?)
`

func (q *Queries) ListLinkIdsByGroupSlugs(ctx context.Context, slugs []string) ([]int64, error) {
	query := listLinkIdsByGroupSlugs
	var queryParams []interface{}
	if len(slugs) > 0 {
		for _, v := range slugs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:slugs*/?", strings.Repeat(",?", len(slugs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:slugs*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var link_id int64
		if err := rows.Scan(&link_id); err != nil {
			return nil, err
		}
		items = append(items, link_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkIdsByGroupType = `-- name: ListLinkIdsByGroupType :many
SELECT CAST(link_id AS INTEGER) AS link_id
FROM link_group lg
   JOIN ` + "`" + `group` + "`" + ` g ON lg.group_id = g.id
WHERE g.type IN (/*SLICE:gts*/?)
`

func (q *Queries) ListLinkIdsByGroupType(ctx context.Context, gts []string) ([]int64, error) {
	query := listLinkIdsByGroupType
	var queryParams []interface{}
	if len(gts) > 0 {
		for _, v := range gts {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:gts*/?", strings.Repeat(",?", len(gts))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:gts*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var link_id int64
		if err := rows.Scan(&link_id); err != nil {
			return nil, err
		}
		items = append(items, link_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkIdsByMetadata = `-- name: ListLinkIdsByMetadata :many
SELECT CAST(link_id AS INTEGER) AS link_id
FROM metadata
WHERE kv_pair IN (/*SLICE:pairs*/?)
`

func (q *Queries) ListLinkIdsByMetadata(ctx context.Context, pairs []string) ([]int64, error) {
	query := listLinkIdsByMetadata
	var queryParams []interface{}
	if len(pairs) > 0 {
		for _, v := range pairs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:pairs*/?", strings.Repeat(",?", len(pairs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:pairs*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var link_id int64
		if err := rows.Scan(&link_id); err != nil {
			return nil, err
		}
		items = append(items, link_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT id, url, created_time, visited_time, created, visited FROM link ORDER BY url LIMIT 100
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.CreatedTime,
			&i.VisitedTime,
			&i.Created,
			&i.Visited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksForGroup = `-- name: ListLinksForGroup :many
SELECT DISTINCT
   id,
   link_id,
   url,
   group_id,
   cast(group_name AS VARCHAR(32)) AS group_name,
   cast(group_slug AS VARCHAR(32)) AS group_slug,
   cast(group_type AS VARCHAR(1))  AS group_type,
   cast(type_name AS VARCHAR(32))  AS type_name,
   domain,
   group_ids,
   group_types,
   group_names,
   quoted_group_types,
   quoted_group_slugs,
   quoted_group_names
FROM
   links_view
WHERE true
   AND group_type = ?
   AND group_slug = ?
ORDER BY
   url
`

type ListLinksForGroupParams struct {
	GroupType string `json:"group_type"`
	GroupSlug string `json:"group_slug"`
}

type ListLinksForGroupRow struct {
	ID               sql.NullInt64  `json:"id"`
	LinkID           sql.NullInt64  `json:"link_id"`
	Url              sql.NullString `json:"url"`
	GroupID          int64          `json:"group_id"`
	GroupName        string         `json:"group_name"`
	GroupSlug        string         `json:"group_slug"`
	GroupType        string         `json:"group_type"`
	TypeName         string         `json:"type_name"`
	Domain           sql.NullString `json:"domain"`
	GroupIds         sql.NullString `json:"group_ids"`
	GroupTypes       sql.NullString `json:"group_types"`
	GroupNames       sql.NullString `json:"group_names"`
	QuotedGroupTypes interface{}    `json:"quoted_group_types"`
	QuotedGroupSlugs interface{}    `json:"quoted_group_slugs"`
	QuotedGroupNames interface{}    `json:"quoted_group_names"`
}

func (q *Queries) ListLinksForGroup(ctx context.Context, arg ListLinksForGroupParams) ([]ListLinksForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinksForGroup, arg.GroupType, arg.GroupSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksForGroupRow
	for rows.Next() {
		var i ListLinksForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Url,
			&i.GroupID,
			&i.GroupName,
			&i.GroupSlug,
			&i.GroupType,
			&i.TypeName,
			&i.Domain,
			&i.GroupIds,
			&i.GroupTypes,
			&i.GroupNames,
			&i.QuotedGroupTypes,
			&i.QuotedGroupSlugs,
			&i.QuotedGroupNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadata = `-- name: ListMetadata :many
SELECT id, link_id, "key", value, kv_pair, created_time, modified_time, created, modified FROM metadata ORDER BY link_id,key DESC
`

func (q *Queries) ListMetadata(ctx context.Context) ([]Metadatum, error) {
	rows, err := q.db.QueryContext(ctx, listMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Metadatum
	for rows.Next() {
		var i Metadatum
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Key,
			&i.Value,
			&i.KvPair,
			&i.CreatedTime,
			&i.ModifiedTime,
			&i.Created,
			&i.Modified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadGroup = `-- name: LoadGroup :one

SELECT id, name, type, slug, created_time, latest_time, created, latest FROM ` + "`" + `group` + "`" + ` WHERE id = ? LIMIT 1
`

// noinspection SqlResolveForFile @ any/"sqlc"
func (q *Queries) LoadGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, loadGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Slug,
		&i.CreatedTime,
		&i.LatestTime,
		&i.Created,
		&i.Latest,
	)
	return i, err
}

const loadGroupType = `-- name: LoadGroupType :one
SELECT type, sort, name, plural, description FROM group_type WHERE type = ? LIMIT 1
`

func (q *Queries) LoadGroupType(ctx context.Context, type_ string) (GroupType, error) {
	row := q.db.QueryRowContext(ctx, loadGroupType, type_)
	var i GroupType
	err := row.Scan(
		&i.Type,
		&i.Sort,
		&i.Name,
		&i.Plural,
		&i.Description,
	)
	return i, err
}

const loadGroupsBySlug = `-- name: LoadGroupsBySlug :one
SELECT id, name, type, slug, created_time, latest_time, created, latest FROM ` + "`" + `group` + "`" + ` WHERE slug = ? LIMIT 1
`

func (q *Queries) LoadGroupsBySlug(ctx context.Context, slug string) (Group, error) {
	row := q.db.QueryRowContext(ctx, loadGroupsBySlug, slug)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Slug,
		&i.CreatedTime,
		&i.LatestTime,
		&i.Created,
		&i.Latest,
	)
	return i, err
}

const loadLink = `-- name: LoadLink :one
SELECT id, url, created_time, visited_time, created, visited FROM link WHERE id = ? LIMIT 1
`

func (q *Queries) LoadLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, loadLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.CreatedTime,
		&i.VisitedTime,
		&i.Created,
		&i.Visited,
	)
	return i, err
}

const upsertGroupsFromVarJSON = `-- name: UpsertGroupsFromVarJSON :exec
INSERT INTO ` + "`" + `group` + "`" + ` (name,type,slug)
SELECT
   json_extract(r.value,'$.name') AS name,
   json_extract(r.value,'$.type') AS type,
   json_extract(r.value,'$.slug') AS slug
FROM var
   JOIN json_each( var.value ) r ON var.key='json'
WHERE var.id = ?
ON CONFLICT (name,type)
   DO UPDATE
   SET latest = strftime('%s','now')
`

func (q *Queries) UpsertGroupsFromVarJSON(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, upsertGroupsFromVarJSON, id)
	return err
}

const upsertLinkGroupsFromVarJSON = `-- name: UpsertLinkGroupsFromVarJSON :exec
INSERT INTO link_group (group_id, link_id)
SELECT g.id, r.id
FROM var
   JOIN json_each( var.value ) j ON var.key='json'
   JOIN link r ON r.url=json_extract(j.value,'$.link_url')
   JOIN ` + "`" + `group` + "`" + ` g ON true
      AND g.name=json_extract(j.value,'$.group_name')
      AND g.type=json_extract(j.value,'$.group_type')
WHERE var.id = ?
ON CONFLICT (group_id, link_id)
   DO UPDATE
            SET latest = strftime('%s','now')
`

func (q *Queries) UpsertLinkGroupsFromVarJSON(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, upsertLinkGroupsFromVarJSON, id)
	return err
}

const upsertLinksFromVarJSON = `-- name: UpsertLinksFromVarJSON :exec
INSERT INTO link (url)
SELECT r.value AS url
FROM var
   JOIN json_each( var.value ) r ON var.key='json'
WHERE var.id = ?
ON CONFLICT (url)
   DO UPDATE
            SET visited = strftime('%s','now')
`

func (q *Queries) UpsertLinksFromVarJSON(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, upsertLinksFromVarJSON, id)
	return err
}

const upsertMetadataFromVarJSON = `-- name: UpsertMetadataFromVarJSON :exec
INSERT INTO metadata (link_id, key, value)
SELECT
   r.id,
   json_extract(kv.value,'$.key'),
   json_extract(kv.value,'$.value')
FROM var
   JOIN json_each( var.value ) kv ON var.key='json'
   JOIN link r ON r.url=json_extract(kv.value,'$.url')
WHERE var.id = ?
   ON CONFLICT (link_id,key)
   DO UPDATE
      SET value = excluded.value
`

func (q *Queries) UpsertMetadataFromVarJSON(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, upsertMetadataFromVarJSON, id)
	return err
}

const upsertVar = `-- name: UpsertVar :execlastid
INSERT INTO var (key,value) VALUES (?,?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type UpsertVarParams struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) UpsertVar(ctx context.Context, arg UpsertVarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertVar, arg.Key, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
